manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/urob
    - name: gpeye
      url-base: https://github.com/GPeye
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: urchin-peripheral-animation
      remote: gpeye
      revision: main 
  self:
    path: config
