manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ftc
    - name: gpeye
      url-base: https://github.com/GPeye
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-ftc
      import: app/west.yml
    - name: urchin-peripheral-animation
      remote: gpeye
      revision: main 
  self:
    path: config
