name: Build ZMK firmware

on:
    workflow_dispatch:
    push:
        paths:
            - "config/**"

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Zephyr environment on Windows
              run: |
                  choco install -y git cmake ninja python3
                  python -m pip install west
                  west init -l app/
                  west update
                  west zephyr-export
                  python -m pip install -r zephyr/scripts/requirements.txt

            - name: Build firmware
              run: |
                  west build -s app -b nice_nano -- -DZMK_CONFIG=config

            - name: Upload firmware
              uses: actions/upload-artifact@v3
              with:
                  name: zmk_firmware
                  path: build/zephyr/zmk.uf2
